<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTWriEzL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTWriEzL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTWriEzL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTWriEzL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTWriEzL\App_KernelDevDebugContainer([
    'container.build_hash' => 'TWriEzL',
    'container.build_id' => 'ffe59f10',
    'container.build_time' => 1634336959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTWriEzL');
