<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvR6ZPN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvR6ZPN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvR6ZPN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvR6ZPN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvR6ZPN\App_KernelDevDebugContainer([
    'container.build_hash' => 'NvR6ZPN',
    'container.build_id' => '628b811c',
    'container.build_time' => 1634329329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvR6ZPN');
