<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.d94b3b43.js',
                '/build/0.57286fb7.js',
                '/build/1.3d7f2d5e.js',
                '/build/app.468ba023.js',
            ],
            'css' => [
                '/build/0.7f5afe90.css',
                '/build/1.6ae7ece4.css',
                '/build/app.d6582cca.css',
            ],
        ],
        'security' => [
            'js' => [
                '/build/runtime.d94b3b43.js',
                '/build/0.57286fb7.js',
                '/build/1.3d7f2d5e.js',
                '/build/security.060e446c.js',
            ],
            'css' => [
                '/build/0.7f5afe90.css',
                '/build/1.6ae7ece4.css',
                '/build/security.24fd7922.css',
            ],
        ],
        'agence' => [
            'js' => [
                '/build/runtime.d94b3b43.js',
                '/build/0.57286fb7.js',
                '/build/1.3d7f2d5e.js',
                '/build/agence.16c2b43c.js',
            ],
            'css' => [
                '/build/0.7f5afe90.css',
                '/build/1.6ae7ece4.css',
                '/build/agence.ebe57043.css',
            ],
        ],
        'admin' => [
            'js' => [
                '/build/runtime.d94b3b43.js',
                '/build/0.57286fb7.js',
                '/build/2.98a823b4.js',
                '/build/admin.c25594cd.js',
            ],
            'css' => [
                '/build/0.7f5afe90.css',
                '/build/2.74e9c340.css',
                '/build/admin.5322876a.css',
            ],
        ],
    ],
],

]];
